AllCops:
  Exclude:
    - 'bin/**/*'
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/AndOr:
  Enabled: false

Style/SignalException:
  Enabled: false # false positives, Puppet's fail is not Kernel's fail

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
